# Generated by Django 5.2.2 on 2025-06-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Naipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome do musico')),
                ('data_nascimento', models.DateField()),
                ('data_ingresso', models.DateField()),
                ('voz', models.CharField(choices=[('1a', 'Primeira Voz'), ('2a', 'Segunda Voz'), ('3a', 'Terceira Voz')], default='1a', max_length=2, verbose_name='voz do instrumento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.instrumento')),
                ('naipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.naipe')),
            ],
        ),
    ]
