# Generated by Django 5.2.2 on 2025-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_musico_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('PRES', 'Presidente'), ('VICE', 'Vice-Presidente'), ('SEC', 'Secretário'), ('TES', 'Tesoureiro'), ('DIR', 'Diretor')], max_length=4)),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
